### ISSUE TITLE
test_bloom build fails because of missing header

### ISSUE THREAD

**Issue by LudwigKnuepfer** [des-testbed/RIOT-projects#26]
`main.c:7:15: fatal error: A.h: No such file or directory`
I guess this should be fixed in the Makefile.

**Comment by OlegHahm** [comment]
You have to build the header file first, using `make sets`, but I agree that the Makefile should check this and generate a proper warning.

**Comment by LudwigKnuepfer** [comment]
Why a warning?
Since this is a dependency it can be modeled as a dependency and build 
by the respective target. That's what Makefiles are for.

**Comment by mehlis** [comment]
In our complex `Makefile` structure I don't know to define the `sets` as a dependency for `all`. If someone has an idea, please add a comment.

**Comment by OlegHahm** [comment]
I thought about setting setting `sets` as a dependency for `all` but that wouldn't make sense, because that would generate different sets for every build, while you might want to just change the code for several builds.

**Comment by mehlis** [comment]
@OlegHahm you are right, so this issue is a `won't fix`

right now the bloom filter implementation only handles c strings, so I have more code changing this to buffers but this code depends on a PRNG...so please ACK on the PRNG PR...

**Comment by OlegHahm** [comment]
Anyway, a warning in the Makefile if no sets have been generated yet would make sense.

**Comment by LudwigKnuepfer** [comment]
What about adding `$(PROJDEPS)` to the `${PROJBINDIR}/%.o` target in `RIOT/Makefile.include` so we can have dependencies for projects?

**Comment by LudwigKnuepfer** [comment]
In order for the dependencies to work as expected this Makefile would then need to be changed like this:

```
export PROJDEPS = A.h

include $(RIOTBASE)/Makefile.include
endif

A.h: generate_sets.py words.txt.gz
    ./generate_sets.py 10000 20
```

**Comment by LudwigKnuepfer** [comment]
... and I see no gain in splitting the data into A.h and B.h ... could be merged while we're at it.

**Comment by LudwigKnuepfer** [comment]
In an off-site discussion with @mehlis he said nothing prevents us from joining `A.h` and `B.h`.
